# Generated by Django 4.2.16 on 2024-12-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0010_auto_20220421_0027"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseguideadjacencylist",
            name="recommended",
            field=models.ManyToManyField(
                related_name="adjacency_list_recommended",
                to="studentservices.courseguidenode",
            ),
        ),
    ]
