# Generated by Django 4.2.16 on 2024-12-04 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0011_courseguideadjacencylist_recommended"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseguideadjacencylist",
            old_name="targets",
            new_name="required",
        ),
    ]
