# Generated by Django 4.2.16 on 2024-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0012_rename_targets_courseguideadjacencylist_required"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseguideadjacencylist",
            old_name="required",
            new_name="target",
        ),
        migrations.RemoveField(
            model_name="courseguideadjacencylist",
            name="recommended",
        ),
        migrations.AddField(
            model_name="courseguideadjacencylist",
            name="type",
            field=models.CharField(
                choices=[("requried", "Required"), ("recommended", "Recommended")],
                default="Required",
                max_length=20,
            ),
        ),
    ]
