# Generated by Django 4.2.16 on 2024-12-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0014_remove_courseguideadjacencylist_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseguideadjacencylist",
            name="recommended",
        ),
        migrations.AddField(
            model_name="courseguideadjacencylist",
            name="type",
            field=models.CharField(
                choices=[("required", "Required"), ("recommended", "Recommended")],
                default="Required",
                max_length=20,
            ),
        ),
    ]
