# Generated by Django 4.2.16 on 2024-12-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "studentservices",
            "0015_remove_courseguideadjacencylist_recommended_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="courseguidenode",
            name="link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
